// Use repository for code or documentation for cloud project write-ups.
export const projects = [
  { id: 'zomato', number: '01', category: 'ELT × ARTIFICIAL INTELLIGENCE', title: 'Millions of rows. One clear view.', subtitle: 'Zomato AI Data Platform', description: 'A modern data stack meets AI: orchestrated transformations, review intelligence, and natural-language queries.', tags: ['Snowflake', 'dbt', 'Airflow', 'LangChain'], metric: '10M+', metricLabel: 'ROWS TRANSFORMED', second: '3', secondLabel: 'INTELLIGENT USE CASES', nodes: ['AWS S3', 'SNOWFLAKE', 'dbt', 'AI APPS'], layers: ['INGEST', 'TRANSFORM', 'ENRICH'], details: ['Built an ELT pipeline on AWS S3 and Snowflake, using dbt and Medallion Architecture to transform a dataset of over 10 million rows.', 'Orchestrated the pipeline with Apache Airflow in Docker, with automated data-quality tests at every layer.', 'Added sentiment enrichment, RAG review search, and text-to-SQL using LangChain, Groq, and Cohere, served through Streamlit.'], fullStack: 'AWS S3 · Snowflake · dbt · Apache Airflow · Docker · LangChain · Groq · Cohere · Streamlit', repository: null },
  { id: 'uber', number: '02', category: 'BATCH + REAL-TIME STREAMING', title: 'Data that never stops moving.', subtitle: 'From Batch to Real-Time: Uber Data Engineering on Azure', description: 'A hybrid batch and streaming pipeline that enriches live Uber ride events into an analytics-ready data model.', tags: ['Event Hubs', 'Databricks', 'PySpark', 'AUTO CDC'], metric: 'HYBRID', metricLabel: 'BATCH + STREAMING', second: 'SCD 2', secondLabel: 'HISTORY-AWARE DIMENSIONS', nodes: ['INGEST', 'SDP', 'OBT', 'STAR SCHEMA'], layers: ['STREAM', 'ENRICH', 'MODEL'], details: ['Explored the shift from finite batch runs to continuously arriving data by building a hybrid batch and streaming pipeline on Azure using Uber ride data.', 'Used Azure Event Hubs for real-time ingestion and Azure Data Factory with ADLS Gen2 for batch ingestion and storage.', 'Processed ride events with Databricks, PySpark, and Spark Declarative Pipelines (SDP), using Streaming Tables and Streaming Joins.', 'Enriched an OBT (One Big Table) with multiple mapping tables, turning raw streaming ride events into an analytics-ready dataset. Used Jinja for metadata-driven PySpark logic.', 'Implemented SCD Type 2 and AUTO CDC, and modeled a final star schema with fact and dimension tables.'], fullStack: 'Azure Event Hubs · Azure Data Factory · ADLS Gen2 · Databricks · PySpark · Spark Declarative Pipelines · Streaming Tables · Streaming Joins · Jinja · SCD Type 2 · AUTO CDC', repository: 'https://github.com/kunalnishad115/UBER_STREAM_AZURE_PROJECT' },
  { id: 'azure', number: '03', category: 'CLOUD DATA ENGINEERING', title: 'Raw reviews. Real insights.', subtitle: 'Amazon Review Analytics', description: 'An end-to-end Azure pipeline that turns product reviews into clean, business-ready analytics.', tags: ['Azure', 'Databricks', 'PySpark', 'Power BI'], metric: '20K+', metricLabel: 'REVIEWS PROCESSED', second: '123', secondLabel: 'PRODUCTS ANALYZED', nodes: ['ADF', 'ADLS', 'DATABRICKS', 'SYNAPSE'], layers: ['BRONZE', 'SILVER', 'GOLD'], details: ['Built a Medallion Architecture pipeline with Azure Data Factory, ADLS Gen2, Databricks, and Azure Synapse Analytics.', 'Developed PySpark ETL to clean and validate more than 20,000 Amazon reviews across 123 products, with zero missing or duplicate records.', 'Created business-ready Gold datasets and Synapse Serverless SQL views, surfaced through interactive Power BI dashboards.'], fullStack: 'Azure Data Factory · Databricks · ADLS Gen2 · PySpark · Azure Synapse Analytics · Power BI', repository: null },
  { id: 'adf', number: '04', category: 'MULTI-SOURCE CLOUD ETL', title: 'Many sources. One trusted layer.', subtitle: 'Multi-Source Azure Data Factory ETL Pipeline', description: 'On-premises systems, Azure SQL, and GitHub APIs connected through an incremental, layered Azure pipeline.', tags: ['Azure Data Factory', 'ADLS Gen2', 'Azure SQL', 'Delta Lake'], metric: '3', metricLabel: 'SOURCE TYPES', second: 'DELTA', secondLabel: 'GOLD-LAYER KPI DATASETS', nodes: ['SOURCES', 'ADF', 'ADLS GEN2', 'DELTA LAKE'], layers: ['BRONZE', 'SILVER', 'GOLD'], details: ['Automated ingestion from on-premises systems, Azure SQL Database, and GitHub REST APIs into ADLS Gen2 using Self-Hosted Integration Runtime and Copy Data pipelines.', 'Organized ingestion and transformation using Medallion Architecture, with ADF Mapping Data Flows for cleansing and schema standardization.', 'Implemented incremental loading through watermarking and generated Gold-layer KPI datasets in Delta Lake.'], fullStack: 'Azure Data Factory · Self-Hosted Integration Runtime · ADLS Gen2 · Azure SQL Database · Delta Lake', documentation: 'https://docs.google.com/document/d/1duzaGe8rhN13898-jjpK1dcq0mCpDUT7p95lPj1xxe0/edit?usp=sharing', repository: null },
  { id: 'rag', number: '05', category: 'RETRIEVAL-AUGMENTED GENERATION', title: 'Answers with a paper trail.', subtitle: 'Hybrid Retrieval RAG Application', description: 'From document ingestion to grounded answers. Hybrid search, intelligent re-ranking, and citations you can follow.', tags: ['Python', 'ChromaDB', 'BM25', 'Streamlit'], metric: 'HYBRID', metricLabel: 'VECTOR + KEYWORD SEARCH', second: 'PDF+', secondLabel: 'MULTI-FORMAT INGESTION', nodes: ['DOCUMENTS', 'CHUNKS', 'RETRIEVAL', 'ANSWERS'], layers: ['EMBED', 'RE-RANK', 'CITE'], details: ['Architected document ingestion for PDF, DOCX, and TXT, including text cleaning, metadata extraction, chunking, and Sentence Transformer embeddings.', 'Combined ChromaDB vector retrieval with BM25 keyword search and cross-encoder re-ranking to improve retrieval relevance.', 'Built a Streamlit application with Gemini and Cohere that grounds generated answers in retrieved chunks and includes inline document and page or section citations.'], fullStack: 'Python · Streamlit · LangChain · ChromaDB · BM25 · Cross-Encoder · Sentence Transformers · Gemini · Cohere · Docker', repository: null },
  { id: 'ragpulse', number: '06', category: 'AI OBSERVABILITY / AIOPS', title: 'Every answer. Fully observed.', subtitle: 'RAGPulse', description: 'An AI observability platform for RAG: request tracing, cost and latency tracking, offline evaluation, and a CI quality gate.', tags: ['LangChain', 'Prometheus', 'Grafana', 'DeepEval'], metric: 'AIOPS', metricLabel: 'TRACING · TOKENS · COST', second: 'CI', secondLabel: 'QUALITY REGRESSION GATE', nodes: ['CHROMA', 'LCEL', 'MISTRAL', 'TELEMETRY'], layers: ['TRACE', 'EVALUATE', 'GATE'], details: ['Built a deliberately simple retrieval pipeline: Streamlit → ChromaDB retrieval → context builder → LangChain LCEL prompt → Mistral response. The focus is the AIOps layer around the pipeline.', 'Traced and timed requests, tracked token usage and cost, and exposed metrics through Prometheus with Grafana visualization.', 'Evaluated faithfulness and answer relevancy offline using DeepEval. An evaluation dataset feeds run_evaluation.py, then regression_gate.py returns pass (exit 0) or fail (exit 1).', 'Integrated the regression gate into GitHub Actions so a quality regression fails the build before deployment. Used Cohere embed-english-v3.0 embeddings, Mistral mistral-small-latest, and uv for package management.'], fullStack: 'Streamlit · ChromaDB · Cohere · Mistral · LangChain (LCEL) · Prometheus · Grafana · DeepEval · GitHub Actions · uv', repository: 'https://github.com/kunalnishad115/RAG-PULSE_AIOPPS' },
];
export const skills = [
  ['01', 'Languages & processing', 'Python', 'SQL', 'PySpark', 'Pandas', 'NumPy'],
  ['02', 'Cloud & data platforms', 'Azure Data Factory', 'Databricks', 'ADLS Gen2', 'Azure Synapse', 'AWS S3', 'Snowflake', 'Delta Lake'],
  ['03', 'Orchestration & DevOps', 'Apache Airflow', 'dbt', 'Docker', 'Git'],
  ['04', 'Databases & storage', 'PostgreSQL', 'MySQL', 'ChromaDB', 'Redis'],
  ['05', 'AI & applications', 'LangChain', 'LangGraph', 'Streamlit', 'RAG', 'Power BI'],
  ['06', 'Observability & evaluation', 'Prometheus', 'Grafana', 'DeepEval', 'GitHub Actions'],
  ['07', 'Streaming & data modeling', 'Azure Event Hubs', 'Spark Declarative Pipelines', 'Streaming Joins', 'SCD Type 2', 'AUTO CDC', 'Jinja'],
];
